'use client';

import { useEffect, useState, FormEvent } from 'react';
import { usePathname } from 'next/navigation';
import { AuthProvider, useAuth } from '@/contexts/AuthContext';
import { ProtectedLayout } from '@/components/layout/ProtectedLayout';
import { engagementsApi, closeoutApi, Engagement, CloseoutReport, EngagementRating, RenewalRecommendation } from '@/lib/api-client';
import styles from './page.module.css';
import Link from 'next/link';

function CloseoutContent() {
  const pathname = usePathname();
  // Expecting /startup/engagements/[id]/closeout or /operator/engagements/[id]/closeout
  const segments = pathname.split('/');
  const engagementId = segments[segments.length - 2];
  
  const { user } = useAuth();
  const isOperator = user?.role === 'OPERATOR';

  const [engagement, setEngagement] = useState<Engagement | null>(null);
  const [report, setReport] = useState<CloseoutReport | null>(null);
  const [ratings, setRatings] = useState<EngagementRating[]>([]);
  const [renewal, setRenewal] = useState<RenewalRecommendation | null>(null);
  
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Rating State
  const [score, setScore] = useState(5);
  const [comments, setComments] = useState('');
  const [submittingRating, setSubmittingRating] = useState(false);

  const fetchAll = async () => {
    try {
      if (!engagementId) return;
      const eng = await engagementsApi.getOne(engagementId);
      setEngagement(eng);
      
      const rep = await closeoutApi.getReport(engagementId).catch(() => null);
      if (!rep && isOperator) {
        // Auto-generate for operator if missing (simplified flow)
        const generated = await closeoutApi.generateReport(engagementId);
        setReport(generated);
      } else {
        setReport(rep);
      }

      const rts = await closeoutApi.getRatings(engagementId).catch(() => []);
      setRatings(rts);

      const ren = await closeoutApi.getRenewal(engagementId).catch(() => null);
      if (!ren) {
        const renGen = await closeoutApi.generateRenewal(engagementId);
        setRenewal(renGen);
      } else {
        setRenewal(ren);
      }

    } catch {
      setError('Failed to load closeout data.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchAll(); }, [engagementId]);

  async function handleSubmitRating(e: FormEvent) {
    e.preventDefault();
    if (!engagement) return;
    setSubmittingRating(true);
    try {
      const revieweeId = isOperator ? engagement.startupId : engagement.operatorId;
      await closeoutApi.submitRating(engagementId, { revieweeId, score, comments });
      alert('Review submitted successfully.');
      fetchAll();
    } catch {
      alert('Failed to submit rating.');
    } finally {
      setSubmittingRating(false);
    }
  }

  if (loading) return <div className={styles.page}><p className={styles.loading}>Loading Closeout Report…</p></div>;
  if (error || !engagement) return <div className={styles.page}><div className={styles.errorBox}><span>⚠</span> {error || 'Not found'}</div></div>;

  const haveRated = ratings.some(r => r.reviewerId === user?.id);

  return (
    <div className={styles.page}>
      <header className={styles.header}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Link href={`/${isOperator ? 'operator' : 'startup'}/engagements/${engagementId}`} className={styles.backLink}>
            ← Back to Workspace
          </Link>
        </div>
        <h1 className={styles.title}>Engagement Closeout & Review</h1>
        <p className={styles.subtitle}>Final report, outcomes, and renewal options for {engagement.contract?.sow.title}.</p>
      </header>

      <div className={styles.layout}>
        {/* Main Column: AI Report & Ratings */}
        <div className={styles.mainCol}>
          
          <section className={styles.section}>
            <h2>Closeout Summary (AI Generated)</h2>
            {report ? (
              <div className={styles.reportCard}>
                <div className={styles.reportSection}>
                  <h3>Executive Summary</h3>
                  <p>{report.summary}</p>
                </div>
                <div className={styles.reportSection}>
                  <h3>Outcomes Achieved</h3>
                  <p>{report.outcomes}</p>
                </div>
                <div className={styles.reportSection}>
                  <h3>Suggested Next Steps</h3>
                  <p>{report.nextSteps}</p>
                </div>
                {report.generatedByAi && (
                  <div className={styles.aiBadge}>✨ Generated by RTIH AI based on workspace activity</div>
                )}
              </div>
            ) : (
              <div className={styles.emptyState}>No report generated yet.</div>
            )}
          </section>

          <section className={styles.section}>
            <h2>Peer Reviews & Ratings</h2>
            {haveRated ? (
              <div className={styles.successBox}>
                Thanks for submitting your review. It helps maintain a high-quality platform.
              </div>
            ) : (
              <div className={styles.reviewFormCard}>
                <h3>Rate your experience</h3>
                <p style={{ fontSize: '0.875rem', color: 'var(--color-text-secondary)', marginBottom: '16px' }}>
                  Please rate the {isOperator ? 'client/startup' : 'operator'} on their communication, delivery, and overall partnership.
                </p>
                <form onSubmit={handleSubmitRating} className={styles.reviewForm}>
                  <div className={styles.field}>
                    <label>Overall Score (1-5)</label>
                    <select value={score} onChange={(e) => setScore(Number(e.target.value))}>
                      {[5, 4, 3, 2, 1].map(n => <option key={n} value={n}>{n} Stars</option>)}
                    </select>
                  </div>
                  <div className={styles.field}>
                    <label>Public Review Comments</label>
                    <textarea value={comments} onChange={(e) => setComments(e.target.value)} rows={4} required placeholder="Leave a brief testimonial or constructive feedback..."></textarea>
                  </div>
                  <button type="submit" className="btn btn-primary" disabled={submittingRating}>
                    {submittingRating ? 'Submitting...' : 'Submit Review'}
                  </button>
                </form>
              </div>
            )}

            <div className={styles.ratingsList}>
              {ratings.map(r => (
                <div key={r.id} className={styles.ratingCard}>
                  <div className={styles.ratingHeader}>
                    <strong>{r.reviewer?.firstName} {r.reviewer?.lastName}</strong>
                    <span className={styles.stars}>{'★'.repeat(r.score)}{'☆'.repeat(5 - r.score)}</span>
                  </div>
                  <p className={styles.ratingComment}>"{r.comments}"</p>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Sidebar: Renewal Recommendation */}
        <div className={styles.sidebar}>
          <section className={styles.section}>
            <h2>Renewal Recommendation</h2>
            {renewal ? (
              <div className={styles.renewalCard}>
                <div className={styles.renType}>
                  {renewal.recommendedType === 'RETAINER_CONVERSION' ? '🔄 Recommended for Retainer' : 
                   renewal.recommendedType === 'FOLLOW_ON_SPRINT' ? '🚀 Recommended for Follow-on Sprint' : 
                   renewal.recommendedType === 'RENEWAL' ? '✅ Renewal Recommended' : 'No Action Recommended'}
                </div>
                <p className={styles.renReason}>{renewal.reasoning}</p>
                
                {renewal.recommendedType !== 'NONE' && !isOperator && (
                  <button className="btn btn-primary" style={{ width: '100%', marginTop: '16px' }}>
                    Draft New Contract
                  </button>
                )}
              </div>
            ) : (
              <div className={styles.emptyState}>No recommendation available.</div>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}

export default function CloseoutPage() {
  return (
    <AuthProvider>
      <ProtectedLayout>
        <CloseoutContent />
      </ProtectedLayout>
    </AuthProvider>
  );
}
